version: '3.8'

services:
  librarydb:
    image: postgres:16
    container_name: librarydb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - library_data:/var/lib/postgresql/data
    restart: no

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - librarydb
    restart: no

volumes:
  library_data: